swagger: '2.0'
info:
  version: '1.0.0'
  title: 'API Docs'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: '127.0.0.1:3000'
basePath: '/api/v1'
schemes:
  - 'http'
paths:
